### ISSUE TITLE
Consider hapi instead of express

### ISSUE THREAD

**Issue by konklone** [konklone/oversight.io#10]
The new npm site [will use it](http://blog.npmjs.org/post/88024339405/nearing-practical-maintainability), it looks [pleasant](http://hapijs.com/tutorials), and Express is [going through some weird stuff](https://github.com/strongloop/express/issues/2264).

The site is still very tiny, so it'd be an easy refactor.

**Comment by parkr** [comment]
Spent the better part of an hour doing this – no luck. Pretty considerable departure from Express, so there's a pretty significant series of changes that go into this. For now, I'd say don't bother. If it becomes a significant pain to use Express, this can be re-evaluated.

**Comment by konklone** [comment]
:+1:
