### ISSUE TITLE
Definitive list of IGs we should have in our database

### ISSUE THREAD

**Issue by konklone** [konklone/oversight.io#16]
It's more than will appear in the IG scraping project. In part, that's because several IGs don't publish reports on their website, or are otherwise FOIA-only. And we'll want to show them, and indicate what we don't have. We also may start supplying reports from them later, if we get FOIAed stuff.

* Capitol Police
* Architect of the Capitol
* NSA
* CIA
* ODNI
* SIGIR

and probably others. Some resources:

* http://crs.wikileaks-press.org/98-141.pdf
* http://fas.org/sgp/crs/misc/R40675.pdf
* http://www.gao.gov/new.items/d09270.pdf

**Comment by divergentdave** [comment]
For reference: https://github.com/unitedstates/inspectors-general/issues/224#issuecomment-89932276

**Comment by divergentdave** [comment]
For reference, OMB's latest list of "designated Federal entities": https://federalregister.gov/a/2014-00210

**Comment by divergentdave** [comment]
I have compiled a mostly-complete list on the [inspector-metadata](https://github.com/konklone/oversight.io/tree/inspector-metadata) branch, along with information about each that might be useful on inspector landing pages. Thoughts? Suggestions?

**Comment by konklone** [comment]
@divergentdave I left some thoughts and suggestions in commit comments. This looks super useful to have, and thank you for putting it together. I'll look for a PR, and consider it as closing this ticket.
