### ISSUE TITLE
Restyle snippet highlighting?

### ISSUE THREAD

**Issue by divergentdave** [konklone/oversight.io#38]
The snippets that Elasticsearch provides are highlighted with &lt;em&gt; tags. I'm not crazy about just using italics for this, I'd prefer either making it bold or keeping it italic and adding a light yellow background. Thoughts?

**Comment by divergentdave** [comment]
Regarding implementation, we can change the tag ES uses with the pre_tag and post_tag options, see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html

On a related note, we should be turning on the HTML "encoder" option.

**Comment by konklone** [comment]
Fixed by #39.
