### ISSUE TITLE
Crontab is getting tight

### ISSUE THREAD

**Issue by konklone** [konklone/oversight.io#8]
Looks like it takes about 50 minutes for the IG crawl to run each hour, even just for 2014 reports, even when most of the reports are already downloaded. That's too tight, it'll start stacking soon.

The simplest solution is to make it a 2 hour delay - it's not that big of a deal.

I could also update the scraper to not bother re-extracting text when the PDF is already downloaded and has already been extracted, that would speed things up a lot. Filed as https://github.com/unitedstates/inspectors-general/issues/73. I'll see how that goes before increasing the crontab.

**Comment by divergentdave** [comment]
@konklone, how long is the crawl taking now?

**Comment by parkr** [comment]
Could you do a checksum to make sure the pdf's haven't changed?

**Comment by divergentdave** [comment]
That part's taken care of now, unitedstates/inspectors-general#220 changed it so that text extraction isn't run if the text file already exists.

**Comment by konklone** [comment]
It looks like the last one took 29 minutes. 

I'm currently running it myself and watching the logs, and there's still plenty of pausing on HTTP requests. Right now I'm looking at a ton of requests like `http://www.cncsoig.gov/news-entry/10-03`, for example. I think the way some scrapers are structured are still just going to be time consuming.

But this is a huge drop -- it was assuredly a lot more than 50 minutes when you took this on -- note that this issue was filed in July 2014, nearly a year ago. We have a lot more scrapers and a lot more rigor now. Minimum, this cut it by half, and I think it likely cut it a lot more.

The cronjob is no longer tight, so I'm closing the issue.
